version: '3.8'
services:
  app:
    build: .
    container_name: ts-node-project-app
    user: root
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/template
    tty: true

  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
