name: Node.js CI
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run suites of tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: yarn install
    
    - name: Run tests
      run: yarn test:ci --forceExit
    
    - name: Lint
      run: yarn lint:fix
      env:
        CI: true
    
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        flag-name: ${{matrix.os}}-node-${{ matrix.node }}
        parallel: true

  build:
    name: Build a docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build image
      run: docker build -t node-template/ci .

  finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@v2
          with:
            github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
            parallel-finished: true